#!/usr/bin/env bash

set +e

exists () {
  command -v "$1" &>/dev/null ;
}

if ! exists unzip ; then
  if [ "$(uname -s)" == "Darwin" ] ; then
    brew install unzip
  else
    sudo apt-get -y --force-yes install unzip
  fi
fi

url="https://github.com/Dieseltime/dotfiles/archive/go.zip"
file="dotfiles.zip"

if exists wget ; then
  fetch=$( wget --no-cache $url -O $file )
elif exists curl ; then
  fetch=$( curl -L -H "Cache-control: no-cache" $url > $file )
fi

$fetch && unzip $file && mv "./dotfiles-go" "$HOME/.dotfiles" && rm $file

source $HOME/.dotfiles/script/bootstrap.sh
