#!/usr/bin/env bash

set +e

exists () {
  command -v "$1" &>/dev/null ;
}

ohai () {
  green='\033[0;32m'
  NC='\033[0m'
  echo -e "${green}$1${NC}"
}

if ! exists unzip ; then
  if [ "$(uname -s)" == "Darwin" ] ; then
    brew install unzip
  else
    sudo apt-get -y --force-yes install unzip
  fi
fi

url="https://github.com/Dieseltime/dotfiles/archive/go.zip"
file="dotfiles.zip"

if exists wget ; then
  fetch=$( wget --quiet --no-cache $url -O $file )
elif exists curl ; then
  fetch=$( curl --silent -L -H "Cache-control: no-cache" $url > $file )
fi

ohai "Downloading dotfiles and extracting ..."
$fetch && unzip -q $file && rm -rf "$HOME/.dotfiles" && mv "./dotfiles-go" "$HOME/.dotfiles" && rm $file

ohai "Bootstrapping ..."
source $HOME/.dotfiles/script/bootstrap.sh
